add aboutus
Dmytro-Tr/yachtadventures pull request #1
Opened 2024-08-08 07:41 UTC by Olegovich86

Доброе утро Дмитрий, добавил свою ветку. Начинаю работать.

2024-08-08 08:38 UTC, Dmytro-Tr requested changes
Отлично. Жду Ваш код. А пока отправляю этот реквкст на "внесение изменений"

2024-08-08 12:28 UTC, Olegovich86 commented
Это черновой вариант, без картинок и разрешения 1440.

2024-08-08 21:24 UTC, Dmytro-Tr requested changes

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  margin-top: -35px;
Змінюємо на margin-top: -59px;
Перевизначаємо, додаємо сюди padding-top: 0;  бо в нас секція налазить на верхню.

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  width: 335px;
Змінюємо на **max-** width: 335px;  робимо її гумовою.

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +.aboutus-container {
Додаємо до контейнера padding: 40px 20px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +@media screen and (min-width: 768px) {
Додаємо зміни для секції, а саме  
.aboutus { margin-top: -67px; }

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .aboutus-container {
Додаємо оновлені падінги   padding-top: 50px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    margin-bottom: 40px;
Змінюємо на margin-bottom: 50px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    height: 187px;
Видаляємо фіксовану висоту, висота може коригуватися контентом

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .first-block {
Намагаємось зробити розташування тексту як на макеті. Додаємо 
max-width: 369px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .aboutus-container {
Краще зробити  позиціювання блоків через flex
display: flex;
justify-content: space-between;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .relative {
Вже flex все робить, тож це все видаляємо
    position: relative;
    left: 733px;
    bottom: 180px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    height: 210px;
Видаляємо фіксовану висоту

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .first-block {
Доводимо вигляд тексту до шаблону за допомогою   max-width: 336px;

2024-08-08 21:24 UTC, Dmytro-Tr commented on src/partials/aboutus.html
> +    <h2 class="title">YachtJet fleet is here to take you on the ultimate adventure</h2>
Задаємо унікальний клас для h2   Наприклад змінюємо на  **class="titletwo"**

2024-08-10 16:01 UTC, Dmytro-Tr requested changes

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  background: linear-gradient(
Цей background: для секції hero. У Вас немає на секції backgroud - видалити

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  border: 1px solid #8e8f99;
У контейнера на макеті немає border - потрібно видалити.

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  height: 423px;
На макеті висота 675px  змінюємо на   max-height: 675px;

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +.aboutus-container {
Ще на контейнер добавляємо  margin-bottom: 140px;  Це буде відступ до наступного контейнера.

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +.cutter {
Тут видаляємо всі падінги
Падінги задамо на контейнер з усіма текстовими блоками.

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +.text-block {
Тут видаляємо всі падінги і марджин також видаляємо
Падінги задамо на контейнер з усіма текстовими блоками.

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  width: 295px;
Щоб добитися вигляду тексту до такого ж як на макеті, пропоную змінити розмір текстового блоку на 
max-width: 280px;

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +@media screen and (min-width: 768px) {
margin-bottom: 351px;  Перевизначаємо відступ до наступної секції
Перевизначити падінги для контейнера з класом  aboutus-position:   padding: 50px 32px;

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    width: 540px;
Тая як я в мобільній версії попросив  змінити на резинову ширину,  то тут також треба поставити 
max-width

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .first-block {
Підігнати текстовий блок по ширині, щоб співпадав із макетом. Наприклад max-width: 370px;

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    height: 390px;
Прибираємо, висота наслідується з мобільної

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .aboutus-position {
Змінюємо padding: 50px 50px 100px;

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    margin-bottom: 100px;
Видаляємо margin-bottom: 100px;  робимо все падінгами

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    padding-top: 50px;
Видаляємо всі падінги звідци.  
Та  додаємо , обнуляємо margin: 0   з розширення для планшетів

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .text-block {
Видаляємо всі падінги і марджин

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +    width: 354px;
Видаляємо ширину, наслідується з планшету

2024-08-10 16:01 UTC, Dmytro-Tr commented on src/css/aboutus.css
> +  .aboutus-container {
margin-bottom: 230px;  Перевизначаємо з планшету для десктопа

2024-08-11 13:38 UTC, Dmytro-Tr approved these changes
Вітаю! Роботу прийнято!

2024-08-11 13:38 UTC, merged