add your yachts
Dmytro-Tr/yachtadventures pull request #2
Opened 2024-08-08 10:10 UTC by DmytroShylin

2024-08-08 19:01 UTC, Dmytro-Tr requested changes

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +  padding-bottom: 80px;
Ставимо верхні та нижні падінги на секцію
padding-top: 40px;
padding-bottom: 40px;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +  max-width: 335px;
Ширина контейнеру у нас 375px.
Видаляємо цю строчку.

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +  background-color: #0e1823;
Такий background-color заданий у загальних стилях для всього body, тож тут його можна видалити.

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yachts-class-item {
Треба добавити прозорість
opacity: 0.4;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yahts-table-spec {
Треба добавити прозорість
opacity: 0.4;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yachts-item-img {
Видалити margin-bottom
Додати padding: 16px 16px 32px

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yachts-option-item {
Видалити padding-bottom: 16px;
  margin-bottom: 16px;
  border-bottom: 1px solid rgba(4, 3, 6, 0.1);
Додати padding: 0 32px 32px;
Зробити лінію

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yahts-table {
Додати padding: 0 32px 32px;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +  .yahts-container {
Змінюємо на секцію 
    padding-bottom: 75px;
    padding-top: 75px;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +    max-width: 690px;
Підігнати розмір, щоб слова переносились, як на макеті. Наприклад max-width: 688px;

2024-08-08 19:01 UTC, Dmytro-Tr commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
Змінити на тег тексту `<p>`

2024-08-08 19:10 UTC, Dmytro-Tr reviewed
Верхній та нижній падінги ми задаємо на секцію, а бокові на контейнер.
Зверніть увагу, у ліжці для картинки бокові падінги одні, для текстової частини бокові падінги інші. Задайте прозорість для частині тексту у картках.  І лінію прийдеться зробити за допомогою псевдо елемента. 
У десктопі  заголовок підігнати до макету, щоб слова переносились як на макеті.

2024-08-09 10:41 UTC, DmytroShylin commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
Тут не згоден
Для SEO заголовки потібні - в цоьму випадку назва яхти яку можна орендувати краще виділити заголовко

а для розмітки це не має ніякого значення

2024-08-09 10:54 UTC, Dmytro-Tr commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
Добре, тоді з розгляду макету можна назначити ці заголовки рангом нижче `<h4>`.   Можемо це питання винести на розгляд всієї групи, якщо схочете.

2024-08-09 10:58 UTC, DmytroShylin commented on src/css/ouryachts.css
> +.yachts-option-item {
Дмитро Питання сугубо освітне 
Я щось упустив і моє рішення в подальшому вплине на щось?

Чи э необхідність **_саме в цьому_** випадку робити лінію псевдоєлементом якщо задача вирішується набагато простіше (бордер ботом)?

2024-08-09 11:01 UTC, DmytroShylin commented on src/css/ouryachts.css
> +    max-width: 690px;
Змінив на 688
Але в мене і на 690 коректне відображення
Мабудь тут треба впроваджувате якесь іньше більш надійне рішення)))

2024-08-09 11:33 UTC, DmytroShylin commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
Если в макете есть заголовки h3 тогда да есть смысл 
В макете есть заголовки H3?

2024-08-09 11:40 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +.yachts-option-item {
Якщо я вірно пам'ятаю, то якщо Ви в такому випадку зробите лінію використовуючи бордер-боттом, то падінгі потягнуть її за собою. Але я можу помилятись. Тож можете зробити, як Вам зручно, але щоб було як на макеті.

2024-08-09 11:46 UTC, Dmytro-Tr commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
Судячи з розміру шрифта, я б використав h3 для імен у картках секції Reviews.  Якщо ми у Вас залишаємо все так як є, треба повідомити людину яка робить секцію Reviews, щоб він/вона використовували h4,  і на цьому питання можна буде закрити.

2024-08-09 11:57 UTC, DmytroShylin commented on src/partials/ouryachts.html
> +          <h3 class="yachts-title-item">ARROW</h3>
ок h4 зроблю - так буде краще по смислу і релівантності заголовків

2024-08-09 14:46 UTC, Dmytro-Tr approved these changes
Ви виконали частину своєї роботи, дякую! Чудова робота! Прийнято!

2024-08-09 14:46 UTC, Dmytro-Tr commented on src/css/ouryachts.css
> +    margin-bottom: 60px;
Вибачаюсь, вчора не написав. Тут margin-bottom:  стає  50px;
Виправте, будь ласка, і роботу буде прийнято!

2024-08-09 18:50 UTC, merged