a project for analysis
Dmytro-Tr/yachtadventures pull request #4
Opened 2024-08-08 17:21 UTC by Seneks999

2024-08-09 07:08 UTC, Dmytro-Tr requested changes
Десктопну версію не перевіряв. Багато вніс поправок, тому все в десктопі вже ламається. Виправте всі вказані недоліки, і повернемось к десктопній версії.
У Вас все виходить! Тож чекаю на Вашу роботу!

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  gap: 50px;
Змінюємо на gap: 80px;

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  background-color: #0e1823;
background-color: transparent;  наслідується від body. Виправляємо

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  max-width: 335px;
Задаємо не фіксовану ширину а відносну
width: 100%

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  padding-top: 14px;
Змінюємо, щоб відступи були з усіх сторін padding: 14px 18px;
Видаляємо padding-top: 14px;   та  padding-left: 18px;

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  margin-bottom: 40px;
Видаляємо margin-bottom: 40px; і назначаємо його на div  в якому знаходиться комент
У `<div>`  прибрати властивість style=""

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  width: 122px;
Не обов'язково ставити, ми ширину задаємо падінгами.

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  height: 46px;
Не обов'язково ставити, ми висоту так само задаємо падінгами.

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +    width: 472px;
Не задаємо фіксовану ширину, краще падінгами вирівняти.
width: 472px;  видаляємо
padding: 0 116px; добавляємо. Чому 116px, бо маємо ще падінги на контейнері, які відняли від тих, що бачимо на макеті

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +    max-width: 472px;
Виправляємо на width: 100%
На div виправляємо margin: 50px

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  .rentayacht-btn {
Не змінили властивості для тексту кнопки. Додаємо
font-size: 18px;
line-height: 1.1;

2024-08-09 07:08 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +@media screen and (min-width: 768px) {
Перевизначаємо для контейнера .rentayacht-container
gap: 100px;

2024-08-09 07:24 UTC, Seneks999 commented
ok, працюю...

2024-08-09 08:17 UTC, Seneks999 commented on src/css/rentayacht.css
> +  gap: 50px;
змінив

2024-08-09 08:18 UTC, Seneks999 commented on src/css/rentayacht.css
> +  background-color: #0e1823;
видалив

2024-08-09 08:23 UTC, Seneks999 commented on src/css/rentayacht.css
> +  max-width: 335px;
width: 100%; задав

2024-08-09 08:25 UTC, Seneks999 commented on src/css/rentayacht.css
> +  padding-top: 14px;
padding: 14px 18px; змінив

2024-08-09 08:45 UTC, Seneks999 commented on src/css/rentayacht.css
> +  margin-bottom: 40px;
Задав class="rentayacht-textarea-box" для div що огортає textarea з placeholder="Comment", та задав туди margin-bottom: 40px;. Властивості style="" не бачу

2024-08-09 09:02 UTC, Seneks999 commented on src/css/rentayacht.css
> +.rentayacht-btn {
зробив

2024-08-09 09:08 UTC, Seneks999 commented on src/css/rentayacht.css
> +    width: 472px;
Фіксовану ширину прибрав, padding: 0 116px; задав

2024-08-09 09:29 UTC, Seneks999 commented on src/css/rentayacht.css
> +    max-width: 472px;
На div який огортає form та h2 задав margin: 50px; На .rentayacht-input {width: 100%;} бачу наслідується від mobile, видалив для tablet ...

2024-08-09 09:35 UTC, Seneks999 commented on src/css/rentayacht.css
> +  .rentayacht-btn {
Властивості для тексту кнопки tablet змінив

2024-08-09 09:51 UTC, Seneks999 commented on src/css/rentayacht.css
> +  width: 122px;
width: 122px; видалив

2024-08-09 09:52 UTC, Seneks999 commented on src/css/rentayacht.css
> +  height: 46px;
height: 46px; видалив

2024-08-09 09:56 UTC, Seneks999 commented on src/css/rentayacht.css
> +@media screen and (min-width: 768px) {
.rentayacht-container {
  display: flex;
  flex-wrap: wrap-reverse;
  gap: 100px;
} призначено для mobile версії

2024-08-09 10:02 UTC, Seneks999 commented
background-color: #0e1823; переніс з .rentayacht-input на tablet на mobile версію. Роблю push, працюю далі. Дякую!

2024-08-10 09:42 UTC, Dmytro-Tr requested changes
Залишились маленькі зауваження. У Вас все вийде. Чекаю на виправлення

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  margin-bottom: 40px;
> Задав class="rentayacht-textarea-box" для div що огортає textarea з placeholder="Comment", та задав туди margin-bottom: 40px;. Властивості style="" не бачу

Перевірив ще раз, у коді у Вас немає style="" для дів. Чомусь у інструменті розробника я його помітив. Тож помилки немає, все ок.

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  margin-bottom: 50px;
margin-bottom: 40px;     У мобільній вірсії відступ до кнопки 40px

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  border: 1px solid rgba(251, 251, 251, 0.5);
border: 1px solid rgba(251, 251, 251, 0.5); Немає у макеті - **видаляємо**
outline: transparent;  Також непотрібно

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  background-color: #0e1823;
Ставимо наслідування кольору background-color: **transparent**; 
 замість background-color: #0e1823;

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  background-color: #0e1823;
Ставимо наслідування кольору background-color: **transparent**; 
замість background-color: #0e1823;

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/partials/rentayacht.html
> +          width="704"
Приберіть фіксовану ширину. Якщо нам потрібно буде, ми задамо її через властивості  .css

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  font-size: 14px;
font-size: 12px;   У мобільній версії  висота шрифту 12px,  далі перевизначаємо на 14px

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +    height: 42px;
height: 54px;   У планшетній версії висота поля стає більшою

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +.rentayacht-btn {
Треба добавити плавності при hover та focus  Наприклад:
transition: background-color 250ms easy-in-out, color 250ms easy-in-out

2024-08-10 09:42 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +@media screen and (min-width: 768px) {
У планшетній версії перевизначаємо висоту шрифту на 14px
.rentayacht-input::placeholder,
.rentayacht-textarea::placeholder {
  font-size: 14px;

2024-08-10 10:10 UTC, Seneks999 commented on src/css/rentayacht.css
> +  margin-bottom: 50px;
Відступ до кнопки на моб. версії margin-bottom: 40px; прописав

2024-08-10 10:16 UTC, Seneks999 commented on src/css/rentayacht.css
> +  border: 1px solid rgba(251, 251, 251, 0.5);
outline: transparent; та  border: 1px solid rgba(251, 251, 251, 0.5); при .rentayacht-btn:focus, .rentayacht-btn:hover видалив

2024-08-10 10:22 UTC, Seneks999 commented on src/css/rentayacht.css
> +  background-color: #0e1823;
Прописав background-color: transparent; замість background-color: #0e1823;

2024-08-10 10:25 UTC, Seneks999 commented on src/css/rentayacht.css
> +  background-color: #0e1823;
Поставив наслідування кольору background-color: transparent; замість background-color: #0e1823;

2024-08-10 10:27 UTC, Seneks999 commented on src/partials/rentayacht.html
> +          width="704"
Фіксовану ширину прибрав

2024-08-10 10:33 UTC, Seneks999 commented on src/css/rentayacht.css
> +  font-size: 14px;
Виправив на font-size: 12px; у мобільній версії. Перепровірив, далі перевизначено на 14px.

2024-08-10 10:35 UTC, Seneks999 commented on src/css/rentayacht.css
> +    height: 42px;
Виправив на height: 54px; у планшетній версії

2024-08-10 10:46 UTC, Seneks999 commented on src/css/rentayacht.css
> +.rentayacht-btn {
Добавив transition: background-color 250ms ease-in-out, color 250ms ease-in-out;

2024-08-10 10:51 UTC, Seneks999 commented on src/css/rentayacht.css
> +@media screen and (min-width: 768px) {
Перевизначив в планшетній версії
.rentayacht-input::placeholder,
  .rentayacht-textarea::placeholder {
    font-size: 14px;
  }

2024-08-10 17:13 UTC, Dmytro-Tr approved these changes
Ви чудово впорались! Робота прийнята!

2024-08-10 17:13 UTC, Dmytro-Tr commented on src/css/rentayacht.css
> +  font-size: 14px;
font-size: 12px;

2024-08-10 17:14 UTC, merged